version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: daily
    ignore:
      # newer versions don't work with the webpack vue-cli wants
      - dependency-name: compression-webpack-plugin
